service: auth-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 20
  environment:
    USER_POOL: ${env:USER_POOL}
    USER_POOL_CLIENT: ${env:USER_POOL_CLIENT}
  httpApi:
    cors: true
    authorizers: 
      userAuthoriser:
        identitySource: $request.header.Authorization
        issuerUrl: "https://cognito-idp.us-east-1.amazonaws.com/${env:USER_POOL}/.well-known/jwks.json"
        audience: 
          - ${env:USER_POOL_CLIENT}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
          - cognito-idp:AdminInitiateAuth
          - cognito-idp:AdminCreateUser
          - cognito-idp:AdminSetUserPassword
          Resource: "*"
         
resources:
  Resources:
    UserPool: 
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${env:USER_POOL}
        Schema: 
          - Name: cpf
            Required: true
            Mutable: true
            AttributeDataType: String
            StringAttributeConstraints:
              MinLength: "11"
              MaxLength: "11"
          - Name: name
            Required: true
            Mutable: true
          - Name: email
            Required: false
            Mutable: true
        Policies:
          PasswordPolicy: 
            MinimumLength: 6
        AutoVerifiedAttributes: []    
    UserClient: 
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${env:USER_POOL_CLIENT}
        GenerateSecret: false
        UserPoolId: 
          Ref: UserPool
        AccessTokenValidity: 5
        IdTokenValidity: 5
        ExplicitAuthFlows: 
          - "ADMIN_NO_SRP_AUTH" 

functions:
  register:
    handler: dist/functions/register.register
    events:
      - httpApi:
          path: /register
          method: post
    role: ${env:LAMBDA_ROLE}

  login:
    handler: dist/functions/login.login
    events:
      - httpApi:
          path: /login
          method: post
    role: ${env:LAMBDA_ROLE}

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
custom:
  serverless-offline:
    useChildProcesses: true
    noAuth: true